scimath/units/pressure.py

I have added the unit 'inches of mercury' to pressure.py. The conversion factor of 1 inHg = 3386.389 Pa was obtained from https://en.wikipedia.org/wiki/Inch_of_mercury.

Added inches of mercury [inHg] to pressure.py

---

CHANGES.txt
scimath/units/tests/has_units_test_case.py
scimath/units/tests/unit_array_test_case.py
scimath/units/unit_array.py

Moved from #4. `UnitArray` comparisons will now return boolean arrays, just like `ndarray`s normally do, and how `UnitArray`s used to behave. I believe that the code that relied on scalar bools coming out has been fixed.

Fix UnitArray comparisons

---

scimath/units/tests/sample_units.py
scimath/units/tests/test_custom_unit_parser.py

@senganal Added a test for your fix in #42 . This extend feature used to work and cannot be broken silently.

Adding unit test for extending unit parser

---

scimath/interpolate/tests/test_basic.py
scimath/units/has_units.py

Recent numpy versions don't like floating point numbers in shape tuples, and also omit some whitespace in array `repr`s.

BUG: Fix tests for compatibility with newer numpy versions.

---

scimath/physical_quantities/units.py
scimath/units/quantity.py
scimath/units/unit_db.py
scimath/units/unit_manager.py

Some of these are obvious typos and refactoring leftovers. There are still
a few in `scimath.physical_quantities` because that package looks like
unfinished work.
Fixes #51 (or what I can of it).

BUG: Clean up NameErrors.

---

scimath/units/unit_parser.py

Restores the parsing of angular minutes and seconds using their "quote mark" special forms.

BUG: Restore angular minutes and seconds parsing.

---

.gitignore
scimath/__init__.py
setup.py

Previously, the dev version was hardcoded in the `__init__` file.
Dev revision numbers are set based on the number of commits since the beginning. For example, if the code is installed from this branch, the version number will be `4.1.3.dev325`
Note that this PR explicitly adds `scipy` as a runtime dependency of the package.
~Note that this PR also explicitly passes `numpy` to the `build_requires` kwarg in `setup`.~

Use git revision based dev version number

---

ci-doc-requirements.txt
docs/source/conf.py
etstool.py

Add/Update commands to install docs-related dependencies into the devenv and to build the docs from the devenv. Thanks to @jjenthought and his work on traits https://github.com/enthought/traits/pull/427 which I happily used here.
Run the following commands to test building the docs 
```
python -m etstool install
python -m etstool docs
python -m SimpleHTTPServer  # On Python 2
```

Use enthought-sphinx-theme for docs

---

MANIFEST.in
pyproject.toml

This PR adds a minimal `pyproject.toml` file to declare NumPy as a build dependency. Without this, a `pip install scimath` in an environment that doesn't have NumPy installed will fail.
See [PEP 518](https://www.python.org/dev/peps/pep-0518/) for more information on use of `pyproject.toml`.
This fixes #76.

Add a pyproject.toml file declaring NumPy as a build dependency.

---

scimath/units/tests/test_unit.py
scimath/units/unit.py

Fixes #87 
The `unit` object does not explicitly define `__hash__`. On Python 2, this is acceptable as `__hash__` will be inherited from `object`. OTOH, on Python 3, `__hash__` will be set to `None`, making `unit` instances unhashable. Note that this behavior is because `unit` defines `__eq__`.
A bug in the existing implementation of `unit` leads to a fundamental issue - in Python, if two objects compare equal, their hash values should be equal. This is not the case on Python 2 at the moment as the default `__hash__` method inherited from `object` will simply return the object's `id`.
This PR fixes the issue by explicitly defining the  `__hash__` method as `hash(("scimath.unit", self.value, self.derivation, self.offset))`, based on Mark's suggestion (see …

Fix unit hash

---

.travis.yml
appveyor.yml
install-edm-linux.sh
install-edm-osx.sh
install-edm-windows.cmd

This PR does two types of changes
1. Update travis to use linux xenial instead of trusty. This involves changing how we use the xfvb service.
2. Update edm to version 2.0.0 on appveyor and travis.

Update CI and use new edm

---

MANIFEST.in

I noticed errors of the type - 
```
...
reading manifest template 'MANIFEST.in'
warning: manifest_maker: MANIFEST.in, line 7: 'recursive-include' expects <dir> <pattern1> <pattern2> ...
warning: manifest_maker: MANIFEST.in, line 8: 'recursive-include' expects <dir> <pattern1> <pattern2> ...
writing manifest file 'scimath.egg-info/SOURCES.txt'
...
```
in the CI job https://travis-ci.com/enthought/scimath/jobs/258169832 .
This is because, as the error message suggests, we are using the wrong format when using `recursive-include`.
This PR fixes that issue.

Use the correct format when recursively including files via Manifest file

---

scimath/units/unit_traits.py

`rich_compare` has been deprecated since version 3.0.3 of triats and it has been replaced with the `comparison_mode` kwarg.
See PR https://github.com/enthought/traits/pull/598/ for more information.

Replace deprecated rich_compare kwarg

---

scimath/units/quantity_trait.py
scimath/units/quantity_traits.py

The `BaseTraitHandler.repr` method was originally deprecated in traits version 3.0.3 and the PR https://github.com/enthought/traits/pull/599 is removing the method entirely.

Remove usage of deprecated methods

---

scimath/physical_quantities/dimensions.py
scimath/units/quantity_traits.py

This PR replaces the uses of the convenience trait types "false" and "DictStrFloat" with "Bool(False)" and "Dict(Str, Float)" respectively.

Replace uses of convenience trait types

---

etstool.py
scimath/units/has_units.py
scimath/units/unit_manager.py
scimath/units/unit_manipulation.py
scimath/units/unit_system.py

Hello,
This PR will fix : 
- 1 typo in `etstool.py`
- 1 typo in `scimath/units/has_units.py`
- 1 typo in `scimath/units/unit_manager.py`
- 2 typos in `scimath/units/unit_manipulation.py`
- 1 typo in `scimath/units/unit_system.py`
Bye! :robot:

docs: fix typos

---

scimath/interpolate/tests/test_basic.py
scimath/units/tests/test_available_imports.py
scimath/units/tests/test_function_signature.py
scimath/units/tests/test_has_units.py
scimath/units/tests/test_scalar_unit.py
scimath/units/tests/test_unit_array.py
scimath/units/tests/test_unit_manipulation.py
scimath/units/unit_db.py

This PR remove unnecessary `if __name__ == "__main__"` blocks from the codebase - most of which are `unittest` related.
Note that there are also instances of potentially broken code in the blocks e.g. importing `hotshot` package or importing `enthought.gotcha`.

Remove unnecessary "if __name__ == '__main__'" code blocks

---

scimath/interpolate/interpolate.py
scimath/mathematics/quaternion.py
scimath/physical_quantities/dimensions.py
scimath/physical_quantities/units.py
scimath/units/function_signature.py
scimath/units/quantity.py
scimath/units/tests/test_unit_array.py
scimath/units/unit.py
scimath/units/unit_array.py
scimath/units/unit_db.py
scimath/units/unit_manager.py
scimath/units/unit_manipulation.py

This PR removes all use of `six` from the codebase.  I suspect CI will fail (hopefully at least) until we stop testing on Python 2.  We can either do that on #104, a standalone PR, or it can be added here.

Remove all use of six

---

.travis.yml
appveyor.yml
etstool.py

We only support Python >= 3.6 now.

Stop testing on Python 2.7 and 3.5

---

.github/workflows/test-with-edm.yml

This PR runs the test suite on github actions.  I made the work flow both a cron job and run on every PR.  Perhaps we should have a separate PR testing against traits from source, and maybe with latest scipy from pip? (scimath only has 2 dependencies - traits and scipy).
I think I will defer those two potential additional cron jobs to a follow up PR once we decide if they are worth it.

Add GitHub Actions CI workflow

---

.github/workflows/bleeding-edge.yml
.github/workflows/test-with-edm.yml

This PR adds a "bleeding edge" cron job following the suggestion of this comment:
https://github.com/enthought/scimath/pull/111#issuecomment-867545918

Bleeding edge cron job

---

scimath/units/meta_quantity.py
scimath/units/quantity.py
scimath/units/style_manager.py
scimath/units/tests/test_meta_quantity.py
scimath/units/tests/test_traits.py
scimath/units/tests/test_units.py
scimath/units/ui/quantity_view.py
scimath/units/unit.py
scimath/units/unit_db.py
scimath/units/unit_manager.py
scimath/units/unit_parser.py
scimath/units/unit_system.py
scimath/units/wx/quantity_editor.py

This PR tries to remove unnecessary `return` statements from the codebase. Note that we checked each instance of `return \n` and removed ones which were redundant. Note that it is possible there are some more `return` statements which are unnecessary.

Remove unnecessary "return" statements

---

scimath/units/smart_unit.py
scimath/units/tests/test_traits.py
scimath/units/tests/test_unit_manipulation.py
scimath/units/unit_converter.py
scimath/units/unit_db.py

This PR removes broken `print` statements, which were potentially used for debugging. Note that I refer to `print` statements, not `print()` function calls. There are still a few, what feel like meaningful, calls to `print()` in the codebase.

Remove broken "print" statements

---

scimath/units/units_version.py

We dont need the `scimath.units.units_version` module anymore as `scimath` is versioned as a whole now. This seems to be a
relic from the days of the `enthought.*` namespace package.

Remove "scimath.units.units_version"

---

scimath/interpolate/interpolate.h

This PR removes an unused variable and so silences a compile-time warning from clang:
```
clang++: scimath/interpolate/_interpolate.cpp
In file included from scimath/interpolate/_interpolate.cpp:4:
scimath/interpolate/interpolate.h:113:23: warning: unused variable 'next_x' [-Wunused-variable]
T next_x;
^
scimath/interpolate/_interpolate.cpp:227:5: note: in instantiation of function template specialization 'block_average_above<double>' requested here
block_average_above((double*)PyArray_DATA((PyArrayObject*)arr_x),
^
1 warning generated.
```

Remove an unused variable

---

ci-doc-requirements.txt
etstool.py

Previously, we were installing `sphinx` from PyPI and `enthought_sphinx_theme` from git/github source. This PR updates the ets utility to install both via EDM.

Use "enthought_sphinx_theme" and "sphinx" from edm

---

etstool.py
scimath/units/tests/test_dimensionless_units.py
scimath/units/tests/test_scalar_unit.py

This PR does the following : 
- Convert a test function `dimensionless_test` into a test method in a `unittest.TestCase` class
- Rename the test method to start with `test_` instead of ending with `_test` to ensure that it gets picked up during unittest test discovery
- Remove unused nose imports
- Use `unittest discover` instead of nose to discover and run the testsuite
- Remove `nose` as a dependency in  the etstool utility

Use unittest to discover and run the testsuite instead of nose

---

scimath/units/tests/test_function_signature.py
scimath/units/tests/test_has_units.py
scimath/units/tests/test_unit_array.py
scimath/units/tests/test_unit_manipulation.py

This PR removes unnecessary calls to `unittest.TestCase` `setUp` and `tearDown` methods.

Remove unnecessary calls to "unittest.TestCase" "setUp" and "tearDown"

---

MANIFEST.in

This PR stops including `scimath.units.plugin.images` in the manifest file. We missed this in #109 .

Stop trying to include "scimath.units.plugin.images" in the manifest file

---

scimath/interpolate/tests/test_basic.py
scimath/units/tests/test_function_signature.py
scimath/units/tests/test_has_units.py
scimath/units/tests/test_meta_quantity.py
scimath/units/tests/test_traits.py
scimath/units/tests/test_unit_array.py
scimath/units/tests/test_unit_manipulation.py
scimath/units/tests/test_units.py

fixes #124 
This PR addresses the following `unittest`-related deprecations and replaces them with the corresponding methods
- `assert_` with `assertTrue`
- `assertEquals` with `assertEqual`
- `failUnlessEqual` with `assertEqual`
- `failUnlessRaises` with `assertRaises`
- `failIf` with `assertFalse`
- `failUnless` with `assertTrue`
- `failIfEqual` with `assertNotEqual`
Additionally, this PR takes the opportinity to rewrite two tests that explicitly call `unittest.TestCase.fail` when an expected error isn't raised to simply use `assertRaises` instead.

Address unittest-related deprecations

---

scimath/units/SI.py
scimath/units/area.py
scimath/units/energy.py
scimath/units/power.py
scimath/units/pressure.py
scimath/units/substance.py
scimath/units/temperature.py
scimath/units/unit.py

Some of the modules in the `scimath.units` subpackage contain a constant `__id__` - which have been removed in this PR. Along with that, there were more "End of file" markers, which have also been removed.

Remove "__id__" and "End of file" markers in `scimath.units.*`

---

scimath/interpolate/interpolate.h
setup.py

This PR:
- Changes the type of variables that hold an index from `int` to `npy_intp` throughout `interpolation.h`
- Silences the NumPy deprecation warning
This should fix the warnings reported in #131, though I haven't tested on Windows. On macOS, under clang with `-Wconversion` I no longer see any warnings about narrowing conversions.
fixes #131

Fix compiler warnings about narrowing conversions

---

TODO.txt

This PR removes the unnecessary/outdated TODO file from the git repository. This might have been used for project management before we moved to GitHub. This file is no longer necessary/relevant.

Remove unnecessary/outdated TODO file

---

appveyor.yml

Code coverage reporting is simply adding noise to the PRs and most of the developers have developed selective blindless towards the reports at the moment.
This PR simply stops reporting code coverage on PRs.

Stop reporting codecov on PRs

---

scimath/units/unit_converter.py

This PR removes the unused/potentially unnecessary/outdated `convert_quantity_old` function from `scimath.units.unit_converter`. Note that I couldn't find any users (internal or external) for the function on GitHub. Ref https://github.com/search?q=convert_quantity_old+extension%3Apy
fixes #118

Remove unused "convert_quantity_old"

---

.readthedocs.yaml
setup.py

This PR adds a basic configuration file for Read the Docs. These changes are based on enthought/traits#1478. This is one more step towards enthought/ets#69.
This PR also add a docs extras_require when installing traitsui to make it easy to build the sphinx docs.

Add a RtD config file

---

scimath/interpolate/interpolate.py
scimath/interpolate/tests/test_basic.py

- `time.clock()` method deprecation fixed with `time.process_time()`.
- `setUp()` method created.
Fixes #149.

`time.clock` Deprecation Fixed

---

.github/workflows/bleeding-edge.yml
.github/workflows/test-with-edm.yml
etstool.py

This PR adds Python 3.8 to the test run.
We should expect the Python 3.8 test runs to fail at the moment, thanks to #149.

Update GitHub Actions workflow to run tests on Python 3.8 as well as 3.6

---

scimath/interpolate/interpolate.py
scimath/units/quantity.py

The `scimath.interpolate.interpolate` main script raise an error about using a float object in a call to `numpy.ones` (actually `scipy.ones`), and warns about uses of deprecation SciPy functions. This PR fixes both the error and the warnings.
Output on main:
```python
(scimath) mdickinson@mirzakhani temp % python -m scimath.interpolate.interpolate
/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py:127: RuntimeWarning: 'scimath.interpolate.interpolate' found in sys.modules after import of package 'scimath.interpolate', but prior to execution of 'scimath.interpolate.interpolate'; this may result in unpredictable behaviour
warn(RuntimeWarning(msg))
/Users/mdickinson/Enthought/ETS/scimath/scimath/interpolate/interpolate.py:140: DeprecationWarning: scipy.arange …
```

Fix errors and warnings from scimath.interpolate.interpolate main script

---

.github/workflows/release-to-pypi.yml
MANIFEST.in
pyproject.toml
setup.py

This is the Traits publication workflow unaltered.  To make it work cleanly,
we needed to:
- add header files to the MANIFEST.in
- set a value for long_description_content_type
- use `oldest-supported-numpy` in the build environment

Add PyPI Publication workflow

---

scimath/units/quantity.py
scimath/units/tests/test_units.py

The original unit conversion done in propagate_data_changes (scimath.units.quantity) can cause conversion error. This PR adds a fix and test for that. closes  issue #171

MAINT: fix unit conversion

---

docs/source/index.rst
docs/source/units/about.rst
docs/source/units/unit_numpy.rst
docs/source/units/user_ref.rst

Our docs are slightly inconsistent about the package name: sometimes its spelled as `SciMath`, sometimes as `Scimath`. As far as I can tell, the intended spelling is `SciMath`.
This PR changes occurrences of `Scimath` to either `SciMath` or `scimath`, depending on context.

Fix SciMath package name

---

scimath/units/SI.py
scimath/units/acceleration.py
scimath/units/angle.py
scimath/units/area.py
scimath/units/convert.py
scimath/units/density.py
scimath/units/dimensionless.py
scimath/units/electromagnetism.py
scimath/units/energy.py
scimath/units/force.py
scimath/units/frequency.py
scimath/units/geo_units.py
scimath/units/length.py
scimath/units/mass.py
scimath/units/power.py
scimath/units/pressure.py
scimath/units/speed.py
scimath/units/substance.py
scimath/units/temperature.py
scimath/units/time.py
scimath/units/volume.py

As mentioned in issue #119 , it can help the users a great bit if we add doc string to the unit api. (Just realized there are so many different metric systems we have around the world...)

DOC: add docstrings to units

---

.github/workflows/test-with-edm.yml

macOS NumPy eggs for EDM are currently incompatible with GitHub-hosted macOS runners: the EDM eggs use AVX2 instructions, which the runners don't support. As a result, our CI jobs are currently failing (see https://github.com/enthought/scimath/actions/runs/4634294059 for an example run):
```
Traceback (most recent call last):
File "setup.py", line 16, in <module>
from numpy import get_include
File "/Users/runner/.edm/envs/scimath-test-3.8/lib/python3.8/site-packages/numpy/__init__.py", line 140, in <module>
from . import core
File "/Users/runner/.edm/envs/scimath-test-3.8/lib/python3.8/site-packages/numpy/core/__init__.py", line 23, in <module>
from . import multiarray
File "/Users/runner/.edm/envs/scimath-test-3.8/lib/python3.8/site-packages/numpy/core/multiarray.py", line 10, in …
```

Don't test on macOS/EDM

---

setup.py

Closes #178
To verify the fix (on a Unix-a-like platform), execute the following instructions from the repository root, replacing the build number in the sdist as appropriate:
```
python -m venv --clear scimath_env
source scimath_env/bin/activate
pip install build
python -m build --sdist
cd dist
pip install scimath-5.1.0.dev423.tar.gz
```
The above works for me on this branch, but on `main` the final `pip install` step fails with an error resembling that reported in #178:
```
(scimath_env) mdickinson@mirzakhani dist % pip install scimath-5.1.0.dev423.tar.gz
WARNING: Requirement 'scimath-5.1.0.dev423.tar.gz' looks like a filename, but the file does not exist
Processing ./scimath-5.1.0.dev423.tar.gz
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: …
```

Replace broken imports from version file in setup script

---

etstool.py

Our bleeding edge tests are failing. This PR may fix that.
Test run: https://github.com/enthought/scimath/actions/runs/8111735158

Use pip install instead of the deprecated python setup.py install

---

.github/workflows/test-with-pypi.yml
setup.py

This PR updates the Python test versions to include Python 3.12 and exclude Python 3.7 (which is now beyond end-of-life).

Add Python 3.12 to test versions; drop Python 3.7

---

.github/workflows/bleeding-edge.yml
.github/workflows/release-to-pypi.yml
.github/workflows/test-with-edm.yml
.github/workflows/test-with-pypi.yml

We're getting warnings about outdated GitHub Actions. This PR brings all actions up to the most recent versions.
~I'm not yet sure whether it's safe to remove the use of GabrielBB/xvfb-action@v1 altogether or whether we need to introduce an explicit use of `xvfb-run -a` on Ubuntu workers. Testing that workflow is currently blocked by the `python setup.py install` failure fixed in #182.~
Update: #182 is merged, and it looks as though everything's working despite the removal of the xvfb-action.
Test run: https://github.com/enthought/scimath/actions/runs/8112365378

Update action versions and EDM version

---

.github/workflows/test-with-pypi.yml

We seem to be using xvfb-run in the `test-with-pypi.yml` GitHub Action, and it's not clear why. This PR removes it.

Don't run tests under xvfb-run unnecessarily

---

.github/dependabot.yml

This PR adds a minimal dependabot config, to reduce the effort needed to keep GitHub Actions up to date.

Add dependabot configuration to keep actions up to date

---

.github/workflows/bleeding-edge.yml

This PR fixes two issues with the bleeding edge workflow - one long-standing, and one recently introduced
- Problem 1: we weren't actually modifying the test environment: the package replacements were happening on the "bootstrap" edm environment ("edm"). So the bleeding edge workflow has apparently not been working as intended for some time.
- Problem 2: the bleeding edge version of Traits now requires Python >= 3.8, so we can't run the tests on Python 3.6.
Successful test run (after a few false starts): https://github.com/enthought/scimath/actions/runs/8112365378

Fix bleeding edge workflow
